const data = {
  contracts: [
    {
      client: 'Vodafone SA',
      slug: 'vodafone-sa',
      category: 'telefonie',
      numar: 123,
      data_inregistrare: '15.10.2024',
      valoare: 12345,
      mod_calcul: 'A',
      data_start: '01.12.2024',
      data_end: '01.12.2025',
      urlPdf: 'p1.pdf',
      description: 'Descrierea pe larg a contractului',
    },
    {
      client: 'Orange SA',
      slug: 'orange-sa',
      category: 'telefonie',
      numar: 123,
      data_inregistrare: '15.10.2024',
      valoare: 12345,
      mod_calcul: 'A',
      data_start: '01.12.2024',
      data_end: '01.12.2025',
      urlPdf: 'p2.pdf',
      description: 'Descrierea pe larg a contractului',
    },
    {
      client: 'Digi SA',
      slug: 'digi-sa',
      category: 'telefonie',
      numar: 123,
      data_inregistrare: '15.10.2024',
      valoare: 12345,
      mod_calcul: 'A',
      data_start: '01.12.2024',
      data_end: '01.12.2025',
      urlPdf: 'p3.pdf',
      description: 'Descrierea pe larg a contractului',
    },
  ],
};
export default data;
